import ERC20_BYTES32_ABI from './ERC20_BYTES32'
import ERC20_ABI from './ERC20'
import MIGRATOR_ABI from './MIGRATOR'
import MULTICALL3_ABI from './MULTICALL3_ABI'
import DIAMOND_ABI from './Diamond'
import MULTI_ACCOUNT_ABI from './MultiAccount'
import COLLATERAL_ABI from './Collateral'

export { ERC20_BYTES32_ABI, MIGRATOR_ABI, MULTICALL3_ABI, DIAMOND_ABI, MULTI_ACCOUNT_ABI, COLLATERAL_ABI, ERC20_ABI }
